//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivityCodesV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Agent { get; set; }
        public string ActivityCode { get; set; }
        public string Description { get; set; }
        public int CallId { get; set; }
    
        public virtual Call Call { get; set; }
    }
}
