//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivityCodesV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call
    {
        public Call()
        {
            this.Activities = new HashSet<Activity>();
        }
    
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
    }
}
